# documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel

cache: packages

# Be strict when checking our package
warnings_are_errors: true

# Needed R packages
r_packages:
  - MBESS

addons:
  apt:
    packages:
    - libgsl-dev # GNU scientific library for MBESS
