# documentation at https://docs.travis-ci.com/user/languages/r

language: r

sudo: true
dist: trusty
cache: packages

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libgsl-dev

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

r_binary_packages:
  - MBESS
